config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  } 

  root "audios#index"
  resources :delivery_traders, only: [:index]
  resources :strangers, only: [:index]
  resources :users, only: [:new, :create, :edit, :update]
  resources :messages, only: [:index, :create, :destroy]
  resources :inquiries, only: [:index, :create]

  # get 'users/show', to: 'users#show'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :user
  
  # imageカラムが空の場合、contentカラムも空であれば保存しない
  validates :content, presence: true, unless: :image? 
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  
  # imageカラムが空の場合、contentカラムも空であれば保存しない
  validates :content, presence: true

  # mount_uploader :image, ImageUploader
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  
  validates :nickname, :email,
            uniqueness: true
  validates :nickname, :email, :password, :encrypted_password,
            presence: true, on: :create
  validates :nickname,
            length: { maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            format: { with: VALID_EMAIL_REGEX }
  validates :password,
            length: { minimum: 6}
  validates :password, confirmation: true

  def self.guest
    find_or_create_by!(email: GUEST_ACCOUNT::GUEST_EMAIL) do |user|
      user.nickname = "guest"
      user.encrypted_password = SecureRandom.urlsafe_base64
      user.password = user.encrypted_password
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def check_guest
    email = resource&.email || params[:user][:email].downcase
    if email == GUEST_ACCOUNT::GUEST_EMAIL
      redirect_to root_path, alert: 'ゲストユーザーの編集・削除はできません。'
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  def index
  end
end

app/controllers/delivery_traders_controller.rb
class DeliveryTradersController < ApplicationController
  def index
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def index
  end
  
  def create
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :message_destroy_user, only: [:destroy]

  def index
    @message = Message.new
    @messages = Message.all.order(created_at: :desc)
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to messages_path, notice: '投稿しました。'
    else
      @message = Message.new
      @messages = Message.all.order(created_at: :desc)
      render :index
    end
  end

  def destroy
    message = Message.where(id: params[:id]).first
    if message.blank?
      return redirect_to(messages_path, alert: "データが見つかりませんでした") 
    else
      message.destroy
      redirect_to messages_path
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def message_destroy_user
    unless Message.find(params[:id]).user.id.to_i == current_user.id
      redirect_to messages_path, notice: '投稿ユーザーではないので削除できません。'
    end
  end

end

app/controllers/strangers_controller.rb
class StrangersController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: %i[update destroy]
  # before_action :correct_user,   only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      bypass_sign_in(@user)
      redirect_to root_path, notice: 'ユーザーを登録しました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      bypass_sign_in(current_user)
      redirect_to root_path, notice: 'ユーザー情報を編集しました。'
    else
      render :edit
    end
  end

  # def show
  #   @user = current_user
  # end

  private
  # 正しいユーザーかどうか確認
  # def correct_user
  #   @user = User.find(params[:id])
  #   redirect_to(root_url) unless current_user?(@user)
  # end

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Inquiries/index.html.haml
-# .wrapper
-#   = render "audios/sidebar"

-# .inquiry-page
-#   .inquiry-page_title
-#     お問い合わせページ

app/views/audios/_sidebar.html.haml
%html
  .side-bar
    .side-bar_title
      %span.outline
        = link_to  "まもるくん", "/"

    %ul.side-bar_menu
      %li
        %i.fas.fa-truck
          = link_to "宅配業者用", delivery_traders_path
      %li
        %i.fas.fa-user-alt-slash
          = link_to "知らない人用", strangers_path

      %li
        %i.fas.fa-chalkboard-teacher
          = link_to "使い方", "/"

      %li
        - if user_signed_in?
          %i.fas.fa-star
            = link_to "アカウント編集", edit_user_registration_path
          %i.fas.fa-door-open
            = link_to "ログアウト",  destroy_user_session_path, method: :delete
          
        - else
          %i.fas.fa-user-circle
            = link_to "ログイン", new_user_session_path
          %i.far.fa-address-card
            = link_to "新規登録", new_user_registration_path
          %i.fas.fa-user-check
            = link_to "ゲストログイン", users_guest_sign_in_path, method: :post
        
      %li
        %i.fas.fa-pen-nib
          = link_to "情報交換ページ", messages_path

      %li
        %i.fas.fa-paper-plane
          = link_to "お問い合わせ", inquiries_path

    .side-bar_copyright
      ©️mamorukun

app/views/audios/_toppage.html.haml
%html
  .main-space
    .main-space_how-to
      .main-space_how-to_title
        使い方
      .main-space_how-to_text
        左側のメニューバーから「宅配業者用」、「知らない人用」を選びます。
        %br お手持ちのPC、スマートフォンのスピーカーをインターホンのマイクに近づけてください。
        適した音声を選び、再生ボタンを押してください。
        %br 男性の声であなたの代わりにインターホン越しに対応します。

    .main-space_sumple
      .main-space_sumple_title
        サンプル音源
      .main-space_sumple_text
        「はーい」
        %br
        %br
        = audio_tag('hai.mp3', id: 'test-audio', controls: "controls", controlslist: "nodownload")

    .main-space_description
      .main-space_description_title
        まもるくん とは・・・
      .main-space_description_text
        女性の一人暮らし、お子さんのお留守番が不安・・・。
        %br 男性が一緒にいてくれたらいいのに。
        %br 男性の声でインターホンに対応することができれば相手に男性がいると思わせることができ、防犯に繋がるのではないかと考えました。
        女性やお子さんが一人で家にいても安心できることを目的として制作したアプリケーションです。

    .main-space_login
      .main-space_login_title
        新規登録・ログイン・ゲストログイン
      .main-space_login_text
        ニックネーム・メールアドレス・パスワードで新規登録・ユーザーログインができます。
        %br 新規登録をすると、以降ログインができるようになります。
        ログインすることで情報交換ページの書き込みが可能です。
        %br 
        %br ゲストログインは登録無しでログインと同等のサービスを利用することができます。
    
    .main-space_account-edit
      .main-space_account-edit_title
        アカウント編集
      .main-space_account-edit_text
        登録されているユーザーの情報を変更・ユーザーの削除ができます。
        %br ゲストユーザーの情報の変更はできません。
      
    .main-space_information
      .main-space_information_title
        情報交換ページ
      .main-space_information_text
        ユーザー様同士での情報交換の為の掲示板です。
        不審者の目撃情報の交換や、お勧めの防犯グッズの紹介などにお使いください。
        %br 誹謗中傷などの不適切な書き込みは見つけ次第削除させていただきます。
    

    .main-space_contact
      .main-space_contact_title
        お問い合わせ（工事中）
      .main-space_contact_text
        お問い合わせ・ご要望がございましたらこちらにお問い合わせください。

app/views/audios/index.html.haml
.wrapper
  = render "sidebar"
  = render "toppage"

app/views/delivery_traders/_delivery_traders.html.haml
%html
  .delivery-traders
    .delivery-traders_title
      宅配業者用

    %ul.delivery-traders_audios
      %li.delivery-traders_audios_voice
        「はーい」
        %br
        %br
        = audio_tag('hai.mp3', id: 'test-audio', controls: "controls", controlslist:"nodownload")

      %li.delivery-traders_audios_voice
        「はい」
        %br
        %br
        = audio_tag('はい.mp3', controls: "controls", controlslist:"nodownload")

      %li.delivery-traders_audios_voice
        「そうです」
        %br
        %br
        = audio_tag('そうです.mp3', controls: "controls", controlslist:"nodownload")

      %li.delivery-traders_audios_voice
        「違います」
        %br
        %br
        = audio_tag('違います.mp3', controls: "controls", controlslist:"nodownload")

      %li.delivery-traders_audios_voice
        (置き配をお願いしたい場合)
        %br
        %br
        「ドアの前に置いていただけますか？」
        %br
        %br
        = audio_tag('ドアの前に置いていただけますか.mp3', controls: "controls", controlslist:"nodownload")

      %li.delivery-traders_audios_voice
        「ありがとうございます」
        %br
        %br
        = audio_tag('ありがとうございます.mp3', controls: "controls", controlslist:"nodownload")

      %li.delivery-traders_audios_voice
        「お願いします」
        %br
        %br
        = audio_tag('お願いします.mp3', controls: "controls", controlslist:"nodownload")

      %li.delivery-traders_audios_voice
        「すみません」
        %br
        %br
        = audio_tag('すみません.mp3', controls: "controls", controlslist:"nodownload")

      %li.delivery-traders_audios_voice
        (音源だけでは対応できなくなった場合、こちらを再生後ご自身でご対応ください)
        %br 
        %br
        「ちょっとわかんないので代わります。ごめん代わってー」
        %br
        %br
        = audio_tag('ちょっとわかんないので代わります。ごめん代わってー.mp3', controls: "controls", controlslist:"nodownload")

app/views/delivery_traders/index.html.haml
.wrapper
  = render "audios/sidebar"
  = render "delivery_traders"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Mamorukun
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/index.html.haml
.wrapper
  = render "audios/sidebar"
  
.message-page
  .message-page_title
    情報交換ページ
  
  .message-page_contents
    - @messages.each do |message|
      .message-page_contents_info{data: {message: {id: message.id}}}
        %p.message-page_contents_info_name
          = message.user.nickname
        %p.message-page_contents_info_date
          = l message.created_at
        - if user_signed_in?
          %p.message-page_contents_info_trash
            = link_to icon('fas', 'trash'), message_path(message), method: :delete, data: { confirm: "投稿を削除しますか？" }

      .message-page_contents_lower
        - if message.content.present?
          %p.message-page_contents_text
            = message.content
          = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

  -# ログインしている場合のみ表示
  - if user_signed_in?
    .form
      = form_for [@message] do |f|
        .input-form
          = f.text_field :content, class: 'input-form_text', placeholder: '入力してください'
          .form_mask
            = f.label :image, class: 'input-form_icon' do
              = icon('fas', 'image', class: 'fa-image')
              = f.file_field :image, class: 'input-form_file'
          = f.submit 'Send', class: 'input-form-btn'

app/views/strangers/_strangers.html.haml
%html
  .strangers
    .strangers_title
      知らない人用

    %ul.strangers_audios
      %li.strangers_audios_voice
        「はーい」
        %br
        %br
        = audio_tag('hai.mp3', id: 'test-audio', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「はい」
        %br
        %br
        = audio_tag('はい.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「どちら様ですか？」
        %br
        %br
        = audio_tag('どちら様ですか.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「どのようなご用件ですか？」
        %br
        %br
        = audio_tag('どのようなご用件ですか？.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「結構です」
        %br
        %br
        = audio_tag('結構です.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「お断りします」
        %br
        %br
        = audio_tag('お断りします.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「お引き取りください」
        %br
        %br
        = audio_tag('お引き取りください.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「困ります」
        %br
        %br
        = audio_tag('困ります.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「違います」
        %br
        %br
        = audio_tag('違います.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「わかりません」
        %br
        %br
        = audio_tag('わかりません.mp3', controls: "controls", controlslist:"nodownload")

      %li.strangers_audios_voice
        「家主が出かけておりまして留守を預かっているだけなので、出直していただけますか？」
        %br
        %br
        = audio_tag('家主.mp3', controls: "controls", controlslist:"nodownload")

app/views/strangers/index.html.haml
.wrapper
  = render "audios/sidebar"
  = render "strangers"